export const ORGANIZATION_PERMISSIONS = [
  'organization:read',
  'organization:update',
  'organization:deactivate',
  'membership:read',
  'membership:invite',
  'membership:update',
  'membership:remove',
  'invitation:read',
  'invitation:create',
  'invitation:resend',
  'invitation:revoke',
  'role:read',
  'role:assign',
  'company:read',
  'company:create',
  'company:update',
  'company:deactivate',
  'branch:read',
  'branch:create',
  'branch:update',
  'branch:deactivate',
  'environment:read',
  'environment:create',
  'environment:update',
  'environment:deactivate',
  'branch-fiscal-profile:read',
  'branch-fiscal-profile:create',
  'branch-fiscal-profile:update',
  'branch-fiscal-profile:confirm',
  'branch-fiscal-profile:deactivate',
  'protheus-parameter-mapping:read',
  'protheus-parameter-mapping:create',
  'protheus-parameter-mapping:validate',
  'tax-strategy:read',
  'tax-strategy:create',
  'tax-strategy:update',
  'tax-strategy:submit-review',
  'tax-strategy:confirm',
  'tax-strategy:deactivate',
  'tax-context:resolve',
] as const;

export type OrganizationPermission = (typeof ORGANIZATION_PERMISSIONS)[number];
