export function setApiTestEnvironment(overrides: Record<string, string> = {}): void {
  Object.assign(process.env, {
    NODE_ENV: 'test',
    API_PORT: '3000',
    API_PREFIX: 'api',
    LOG_LEVEL: 'silent',
    CORS_ORIGINS: 'http://localhost:4200,http://localhost:4300',
    APP_VERSION: '0.1.0',
    OPENAPI_ENABLED: 'true',
    APP_WEB_URL: 'http://localhost:4200',
    SESSION_COOKIE_NAME: 'tes_session',
    SESSION_TTL_SECONDS: '43200',
    SESSION_SECURE_COOKIE: 'false',
    SESSION_SAME_SITE: 'lax',
    CSRF_HEADER_NAME: 'X-CSRF-Token',
    EMAIL_VERIFICATION_TTL_SECONDS: '86400',
    PASSWORD_RESET_TTL_SECONDS: '1800',
    AUTH_LOGIN_LIMIT: '5',
    AUTH_LOGIN_WINDOW_SECONDS: '900',
    AUTH_EMAIL_LIMIT: '3',
    AUTH_EMAIL_WINDOW_SECONDS: '3600',
    ORGANIZATION_INVITATION_TTL_SECONDS: '604800',
    ORGANIZATION_INVITATION_RESEND_LIMIT: '3',
    ORGANIZATION_INVITATION_RESEND_WINDOW_SECONDS: '3600',
    ORGANIZATION_HEADER_NAME: 'X-Organization-ID',
    EMAIL_PROVIDER: 'fake',
    EMAIL_FROM_NAME: 'TES Engine',
    EMAIL_FROM_ADDRESS: 'no-reply@tes-engine.local',
    SMTP_HOST: '127.0.0.1',
    SMTP_PORT: '1025',
    SMTP_SECURE: 'false',
    SMTP_USER: '',
    SMTP_PASSWORD: '',
    RESEND_API_KEY: '',
    RESEND_FROM_ADDRESS: '',
    DATABASE_URL: 'postgresql://tes_engine_app:change-me@127.0.0.1:15432/tes_engine',
    DATABASE_POOL_MIN: '0',
    DATABASE_POOL_MAX: '5',
    DATABASE_CONNECTION_TIMEOUT_MS: '1000',
    DATABASE_QUERY_TIMEOUT_MS: '2000',
    DATABASE_HEALTH_TIMEOUT_MS: '1000',
    ...overrides,
  });
}
