export type SourceAuthorityLevel =
  | 'PRIMARY_NORMATIVE'
  | 'PRIMARY_VENDOR'
  | 'ENVIRONMENT_SNAPSHOT'
  | 'INTERNAL_DECISION'
  | 'SECONDARY_TECHNICAL'
  | 'COMMUNITY_REFERENCE';

export type SourceKind =
  | 'OFFICIAL_LEGISLATION'
  | 'OFFICIAL_SCHEMA'
  | 'OFFICIAL_VENDOR_DOCUMENTATION'
  | 'VENDOR_KNOWLEDGE_BASE'
  | 'PROJECT_ARCHITECTURE'
  | 'THIRD_PARTY_TECHNICAL_CATALOG'
  | 'SYNTHETIC_EVIDENCE';

export type ResearchDomain =
  | 'PROTHEUS_MILE'
  | 'PROTHEUS_SX3'
  | 'PROTHEUS_SF4'
  | 'CONFIGTRIB'
  | 'NFE'
  | 'RESEARCH_GOVERNANCE';

export type ResearchRecordStatus =
  | 'DRAFT'
  | 'UNDER_REVIEW'
  | 'VERIFIED'
  | 'VERIFIED_WITH_LIMITATIONS'
  | 'REJECTED'
  | 'SUPERSEDED'
  | 'OBSOLETE';

export type ClaimScopeKind = 'GLOBAL' | 'COUNTRY' | 'STATE' | 'RELEASE' | 'TENANT_ENVIRONMENT';

export type EvidenceKind =
  | 'OFFICIAL_PAGE'
  | 'OFFICIAL_SCHEMA'
  | 'OFFICIAL_DOCUMENT'
  | 'INTERNAL_DOCUMENT'
  | 'TECHNICAL_CATALOG_LOCATOR'
  | 'SYNTHETIC_XML'
  | 'MANUAL_OBSERVATION';

export type ConflictResolutionStatus =
  | 'OPEN'
  | 'ACCEPTED_LIMITATION'
  | 'RESOLVED_BY_AUTHORITY'
  | 'RESOLVED_BY_ENVIRONMENT'
  | 'DEFERRED';

export type ResearchDecisionStatus = 'PROPOSED' | 'ACCEPTED' | 'REJECTED' | 'SUPERSEDED';
