export const TAX_STRATEGY_ERROR_CODES = [
  'TAX_STRATEGY_NOT_FOUND',
  'TAX_STRATEGY_ALREADY_CONFIRMED',
  'TAX_STRATEGY_IMMUTABLE',
  'TAX_STRATEGY_INCOMPLETE',
  'TAX_STRATEGY_MODE_MISMATCH',
  'TAX_STRATEGY_OVERLAP',
  'TAX_STRATEGY_INVALID_PERIOD',
  'TAX_DOMAIN_NOT_FOUND',
  'TAX_DOMAIN_DUPLICATED',
  'TAX_OWNER_INVALID',
  'NOT_APPLICABLE_REASON_REQUIRED',
  'CONFIRMED_FISCAL_PROFILE_REQUIRED',
  'TAX_CONTEXT_NOT_AVAILABLE',
  'VERSION_CONFLICT',
] as const;

export type TaxStrategyErrorCode = (typeof TAX_STRATEGY_ERROR_CODES)[number];
